# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Create_Team_Dialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Main_Window as MW


class Ui_Form(object):
    TeamName=""
    def newTeam(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=MW.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.ui.l7.setText(Ui_Form.TeamName)
        self.window.show()

    def setupUi(self, Form):
        self.Form=Form
        Form.setObjectName("Form")
        Form.resize(375, 199)
        Form.setStyleSheet("font: bold italic 9pt \"Comic Sans MS\";\n"
"background-image:url(\"c.jpeg\")\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.le1 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le1.setFont(font)
        self.le1.setText("")
        self.le1.setObjectName("le1")
        self.gridLayout.addWidget(self.le1, 0, 1, 1, 1)
        self.b1 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.gridLayout.addWidget(self.b1, 2, 0, 1, 2)
        self.le2 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.le2.setFont(font)
        self.le2.setObjectName("le2")
        self.gridLayout.addWidget(self.le2, 1, 1, 1, 1)
        self.b1.clicked.connect(self.create_team)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # self.b1.clicked.connect(self.cl)
    
    def create_team(self):
        Ui_Form.TeamName=self.le1.text()
        self.newTeam()
        self.team_name = self.le1.text()
        self.match_number = self.le2.text()

        if self.team_name and self.match_number:
            QtWidgets.QMessageBox.information(None, "Success", f"Team '{self.team_name}' for match '{self.match_number}' created successfully!")
            # QtWidgets.QWidget().close()
            self.Form.accept()
        else:
            QtWidgets.QMessageBox.warning(None, "Input Error", "Please enter both team name and match number.")
        if self.team_name and self.match_number:
            QtWidgets.QWidget().close()
        
    
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Create Team"))
        self.label.setText(_translate("Form", "New Team Name"))
        self.label_2.setText(_translate("Form", "Match Number"))
        self.b1.setText(_translate("Form", "Create Team"))

    # def cl(self):
    #     self.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog= QtWidgets.QDialog()
    ui = Ui_Form()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
