# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Open_Team_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3



class Ui_Form(object):
    team_score=0
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(645, 559)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        Form.setFont(font)
        Form.setStyleSheet("font: bold italic 9pt \"Comic Sans MS\";\n""background-image:url(\"c.jpeg\")\n""")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.list2 = QtWidgets.QListWidget(Form)
        self.list2.setStyleSheet("background-image:url(\"d.jpeg\")\n""")
        self.list2.setObjectName("list2")
        self.horizontalLayout_2.addWidget(self.list2)
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(Form)
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.horizontalLayout_2.addWidget(self.verticalScrollBar_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 2, 1, 2)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 2, 1, 1)
        self.cb2 = QtWidgets.QComboBox(Form)
        self.cb2.setObjectName("cb2")
        self.cb2.addItem("")
        self.gridLayout.addWidget(self.cb2, 1, 2, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b1 = QtWidgets.QPushButton(Form)
        self.b1.setObjectName("b1")
        self.horizontalLayout_4.addWidget(self.b1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 6, 0, 1, 4)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 4)
        self.cb1 = QtWidgets.QComboBox(Form)
        self.cb1.setStyleSheet("")
        self.cb1.setObjectName("cb1")
        self.cb1.addItem("")
        
        self.gridLayout.addWidget(self.cb1, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 4)
        self.l1 = QtWidgets.QLabel(Form)
        self.l1.setObjectName("l1")
        self.l1.setStyleSheet("color:blue;")
        self.gridLayout.addWidget(self.l1, 3, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.list1 = QtWidgets.QListWidget(Form)
        self.list1.setStyleSheet("background-image:url(\"d.jpeg\")\n"
"")
        self.list1.setObjectName("list1")
        self.horizontalLayout.addWidget(self.list1)
        self.verticalScrollBar = QtWidgets.QScrollBar(Form)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout.addWidget(self.verticalScrollBar)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.list1.clear()

        TEAMS=sqlite3.connect("FantasyCricketApp.db")
        curteams=TEAMS.cursor()
        sql="select NAME from TEAMS;"
        curteams.execute(sql)
        teams=curteams.fetchall()
        for team in teams:
            self.cb1.addItem(str(team)[2:-3])
        self.cb2.addItem("Match 1")
        self.cb2.addItem("Match 2")
        self.cb2.addItem("Match 3")
        self.cb2.addItem("Match 4")
        self.cb2.addItem("Match 5")
        self.b1.clicked.connect(self.EvaluateScore)
        self.cb1.currentTextChanged.connect(self.ChangePlayers)
        self.cb2.currentTextChanged.connect(self.ChangeScore)

    def ChangePlayers(self):
        TEAMS=sqlite3.connect("FantasyCricketApp.db")
        curteams=TEAMS.cursor()
        sql2="select players from teams where name= '"+self.cb1.currentText()+"';"
        curteams.execute(sql2)
        players=curteams.fetchall()
        for player in players:
            play=player[0].split(',')
            for i in range(len(play)):
                if i==len(play)-1:
                    self.list1.addItem(play[i][2:-2])
                else:
                    self.list1.addItem(play[i][2:-1])

    def Batting(self,player):

        points=0
        try:
            strike_rate=(player[1]/player[2])*100
            points=points+(player[1]//2)
            if player[1]>=50:
                points=points+5
            if player[1]>=100:
                points=points+10
            if strike_rate >=80 and strike_rate <=100:
                points=points+2
            elif strike_rate >100:
                points=points+4
            points=points+player[3]+(2*player[4])
        except:
            pass
        return points
    
    def Bowling(self,player):
        points=0
        # bowl_scores=[]
        try:
            economy=player[7]//(player[5]/6)
            points=points+player[8]*10
            if player[8]==3:
                points=points+5
            elif player[8]>=5:
                points=points+10
            if economy >= 3.5 and economy<=4.5:
                points=points+4
            elif economy >= 2 and economy<=3.5:
                points=points+7
            elif economy < 2:
                    points=points+10  
        except:
            pass
        return points
    def Fielding(self,player):
        points=0
        try:
            points+=(player[9]+player[10]+player[11])*10
        except:
            pass
        return points
    
    def ChangeScore(self):
        Ui_Form.team_score=0
        self.list2.clear()
        players_list=[]
        for item in [self.list1.item(i).text() for i in range(self.list1.count())]:
            points=sqlite3.connect("FantasyCricketApp.db")
            curplay=points.cursor()
            sql="Select * from match where PLAYER='"+item+"';"
            curplay.execute(sql)
            players_list.append(curplay.fetchone())
        for item in players_list:
            player_score=0
            player_score+=self.Batting(item)
            player_score+=self.Bowling(item)
            player_score+=self.Fielding(item)
            Ui_Form.team_score+=player_score
            self.list2.addItem(str(player_score))
    def EvaluateScore(self):
        self.l1.setText(str(Ui_Form.team_score))   

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Open Team"))
        self.label_2.setText(_translate("Form", "Points :"))
        self.cb2.setItemText(0, _translate("Form", "Select Match"))
        self.b1.setText(_translate("Form", "Calculate Score"))
        self.label_3.setText(_translate("Form", "Evaluate performance of your team"))
        self.cb1.setItemText(0, _translate("Form", "Select Team"))
        self.l1.setText(_translate("Form", "0"))
        self.label.setText(_translate("Form", "Players"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
